"""empty message

Revision ID: ad7185da3144
Revises: 3ece14fd8be0
Create Date: 2019-01-31 13:16:56.302692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad7185da3144'
down_revision = '3ece14fd8be0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('izlet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('description', sa.String(length=140), nullable=True),
    sa.Column('location', sa.String(length=140), nullable=True),
    sa.Column('transport', sa.String(length=70), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('begin', sa.Date(), nullable=True),
    sa.Column('end', sa.Date(), nullable=True),
    sa.Column('picture', sa.String(length=200), nullable=True),
    sa.Column('cost', sa.Numeric(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_izlet_begin'), 'izlet', ['begin'], unique=False)
    op.create_index(op.f('ix_izlet_end'), 'izlet', ['end'], unique=False)
    op.create_index(op.f('ix_izlet_timestamp'), 'izlet', ['timestamp'], unique=False)
    op.drop_index('ix_post_timestamp', table_name='post')
    op.drop_table('post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.VARCHAR(length=140), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_post_timestamp', 'post', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_izlet_timestamp'), table_name='izlet')
    op.drop_index(op.f('ix_izlet_end'), table_name='izlet')
    op.drop_index(op.f('ix_izlet_begin'), table_name='izlet')
    op.drop_table('izlet')
    # ### end Alembic commands ###
